version: '3'
services:
  keycloak:
    image: coopersoft/keycloak:21.0.1_phone-2.2.2
    #    restart: always
    ports:
      - "8080:8080"
    command:
      - start-dev --spi-phone-default-service=aliyun \
        --spi-message-sender-service-aliyun-region=cn-hangzhou \
        --spi-message-sender-service-aliyun-key=${accessKey} \
        --spi-message-sender-service-aliyun-secret=${accessSecret} \
        --spi-message-sender-service-aliyun-otp-template={templateId}
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
  #      KC_PROXY: edge
  #      DB_VENDOR: mariadb
  #      DB_ADDR: database
  #      DB_DATABASE: keycloak
  #      DB_USER: keycloak
  #      DB_PASSWORD: k@ycl0ck
  #      DB_PORT: 3306
  #    links:
  #      - database:database
  #    depends_on:
  #      - database

  healthcheck:
    image: curlimages/curl:latest
    command:
      - "sh"
      - "-c"
      - >
        while true; do
          sleep 3600;
        done
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://keycloak:8080/health" ]
      interval: 10s
      timeout: 60s
      retries: 5
    depends_on:
      - keycloak
    links:
      - keycloak:keycloak
